import { writable } from 'svelte/store'

export const Resources = writable([])
/* let resources = [
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 1, name: 'Ken', maxHours: 40 },
    { id: 2, name: 'Apple', maxHours: 10 },
    { id: 3, name: 'Marlong', maxHours: 15 }
] */
